sudo: false
language: python
python:
  - "2.7"
  - "3.3"

install:
  # Install `planet_rest_api`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

script:
  # Run our tests
  - bin/test.sh

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
