sudo: false
language: python
python:
  - "2.7"

install:
  # Upgrade Travis CI's `pip` to avoid install issues
  - pip install --upgrade pip

  # Bootstrap our package via same script as users
  - bin/bootstrap.sh

script:
  # Run our tests
  - bin/test.sh

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
