sudo: false
language: python
python:
  - "2.7"

install:
  # Install `planet_rest_api`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
